-- 소스 테이블 조회 
SELECT *
  FROM LRM.EMP_SRC
 ORDER BY EMP_ID
;


-- (스트리밍 테스트 시 사용) 신규 INSERT / 변경 UPDATE 예시
-- INSERT INTO EMP_SRC (EMP_ID, EMP_NAME, DEPT_CD, SALARY, HIRE_DATE) VALUES (1004, '최지훈', 'IT02', 5000000, SYSDATE);
-- UPDATE EMP_SRC SET SALARY = SALARY * 1.1 WHERE EMP_ID = 1001;
-- COMMIT;


-- 타겟 테이블 조회 
SELECT *
  FROM LRM.EMP_TGT
 ORDER BY EMP_ID
;
